### PR TITLE
Tweaks for 2024

### PR DESCRIPTION
**Pull request by julianstirling**
Hello I tweaked a few things that were a little out of date:

* Prusa's 3D repo is now called Printables (url changed)
* Added Onsdel Lens to 3D repos
* OpenFlexure Microscope linked to a sub-project rather than the main microscope
* Added the other OpenFlexure projects
* Added repo for the OpenFlexure Software
* Added the OpenFlexure Forum
* Fixed the GitHub link for UC2

### CODE REVIEW

**Comment by beniroquai** [comment]
Great! Thanks a lot @julianstirling for the updates. And great, too: I learned about new projects. 

Maybe a general question @jhohlbein - should we convert this beautiful database into something more "human readable" by means of a github website? Just a random thought.

**Comment by jhohlbein** [comment]
Thanks @julianstirling for the edits!

Re @beniroquai: You don't like browsing through long Excel-like lists? Just kidding. My idea would be to have a site that dynamically links against the Github repo, but has, for example, a search function baked in. E.g., look for all entries about SMLM. No idea how to implement that though.

**Comment by beniroquai** [comment]
like this?
https://openuc2.github.io/

**Comment by julianstirling** [comment]
Would be easy enough to implement via GitHub Actions with Jekyll or any other static site generator. Probably best to do it via actions rather than the old ugly hack of having a pages branch on GitHub.

**Comment by jhohlbein** [comment]
Feel free :) I am already happy when people add some new projects every now and then.

**Comment by julianstirling** [comment]
While it is ugly (could be tweaked) to look nice.. What we did for tabulated data for the OpenFlexure Failure mode analysis was to make a searchable sortable table:
https://openflexure.gitlab.io/microscope-failure-mode-analysis/manufacturing.html

**Comment by beniroquai** [comment]
With react, everything becomes nice :D 
https://pester.dev/docs/additional-resources/articles/

**Pull request merged**
